/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import models.DBManager;
import models.Heatpump;
import models.Product;
import models.Replacement_Parts;
import models.SolarPanel;
import models.Staff;

/**
 *
 * @author thomm
 */
public class AddProduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddProduct.class.getName());

     private static final String DB_URL = "jdbc:ucanaccess://Data/ShopDB.accdb";
  
    private Staff loggedInStaff;
    /**
     * Creates new form AddProduct
     */
    public AddProduct(Staff staffIn) {
        DBManager db = new DBManager();
        
        initComponents();
        
        this.loggedInStaff = staffIn;  
        
        ButtonGroup group =  new ButtonGroup();
        group.add(rdoBtnSolarPanel);
        group.add(rdoBtnHeatPump);
        group.add(rdoBtnReplacementPart);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rdoBtnSolarPanel = new javax.swing.JRadioButton();
        rdoBtnHeatPump = new javax.swing.JRadioButton();
        rdoBtnReplacementPart = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        txtWattage = new javax.swing.JTextField();
        txtEfficiency = new javax.swing.JTextField();
        txtPartFor = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnConfirmCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Category:");

        rdoBtnSolarPanel.setText("Solar Panel");

        rdoBtnHeatPump.setText("Heat Pump");

        rdoBtnReplacementPart.setText("Replacement Part");

        jLabel2.setText("Product Name:");

        jLabel3.setText("Price:");

        jLabel4.setText("Stock Level:");

        jLabel6.setText("Wattage Output:");

        jLabel7.setText("Efficiency Rating:");

        jLabel8.setText("Part For:");

        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirmCategory.setText("Confirm");
        btnConfirmCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEfficiency, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWattage, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPartFor, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoBtnSolarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoBtnHeatPump)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoBtnReplacementPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(275, 275, 275))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnConfirmCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdoBtnSolarPanel)
                    .addComponent(rdoBtnHeatPump)
                    .addComponent(rdoBtnReplacementPart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmCategory)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtWattage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEfficiency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPartFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnBack))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ProductMenu productMenu = new ProductMenu(this.loggedInStaff);
        productMenu.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        
        
        String productName = txtProductName.getText();
        if(productName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Product Name cannot be empty");
            return;
        }
        
        double price = 0;
        int stock = 0;
        
        try
        {
            price = Double.parseDouble(txtPrice.getText());
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: Price should be an Integer");
            return;
        }
        
        try
        {
            stock = Integer.parseInt(txtStockLevel.getText());
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: Stock Level should be an Integer");
            return;
        }
        
        Product productToAdd = null;
        
        if (rdoBtnSolarPanel.isSelected())
        {
            try
            {
                int wattage = Integer.parseInt(txtWattage.getText());
                productToAdd = new SolarPanel(productName, price, stock, wattage);
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error: Wattage should be an Integer");
                return;
            }
        }
        else if (rdoBtnHeatPump.isSelected())
        {
            try
            {
                double efficiency = Double.parseDouble(txtEfficiency.getText());
                productToAdd = new Heatpump(productName, price, stock, efficiency);
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error: Stock Level should be an Integer");
                return;
            }
        }
        else if (rdoBtnReplacementPart.isSelected())
        {
            String partFor = txtPartFor.getText();
            if(partFor.isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "Error: 'Part For' cannot be empty");
                return;
            }
            productToAdd = new Replacement_Parts(productName, price, stock, partFor);
        }
        
        if (productToAdd != null)
        {
            DBManager db = new DBManager();
            if (db.addProduct(productToAdd))
            {
                JOptionPane.showMessageDialog(this,"Product Succeffully Created");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error Saving product to the database");
            }
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnConfirmCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmCategoryActionPerformed
        // TODO add your handling code here:
        
        if (rdoBtnSolarPanel.isSelected())
        {
            txtEfficiency.setEnabled(false);
            txtPartFor.setEnabled(false);
            txtWattage.setEnabled(true);
        }
        else if (rdoBtnHeatPump.isSelected())
        {
            txtPartFor.setEnabled(false);
            txtWattage.setEnabled(false);
            txtEfficiency.setEnabled(true);
        }
        else if (rdoBtnReplacementPart.isSelected())
        {
            txtEfficiency.setEnabled(false);
            txtWattage.setEnabled(false);
            txtPartFor.setEnabled(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error: Choose one of the Category");
        }
    }//GEN-LAST:event_btnConfirmCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AddProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rdoBtnHeatPump;
    private javax.swing.JRadioButton rdoBtnReplacementPart;
    private javax.swing.JRadioButton rdoBtnSolarPanel;
    private javax.swing.JTextField txtEfficiency;
    private javax.swing.JTextField txtPartFor;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtStockLevel;
    private javax.swing.JTextField txtWattage;
    // End of variables declaration//GEN-END:variables
}
