/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.DBManager;
import models.Order;
import models.OrderLine;
import models.Product;

/**
 *
 * @author 30512007
 */
public class Basket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Basket.class.getName());
    
    private Order currentBasket;
    private Customer loggedInCustomer;
    
    /**
     * Creates new form Basket
     */
    public Basket() {
        initComponents();
    }
    
        
    public Basket (Order basketIn, Customer customerIn)
    {
        initComponents();
        
        this.currentBasket = basketIn;
        this.loggedInCustomer = customerIn;
        
        lblTotalPrice.setText("Total: £" + String.format("%.2f", currentBasket.getOrderTotal()) );
                
        populateTable();
    }
    

    
    private void populateTable()
    {
        DefaultTableModel powerModel = (DefaultTableModel) lstOrders.getModel();
        
        powerModel.setRowCount(0);
        
        for (Map.Entry<Integer, OrderLine> ol: currentBasket.getOrderLines().entrySet())
        {
            OrderLine actualOrderLine = ol.getValue();
            Product product = actualOrderLine.getProductBought();
            
            // Create an array of data for the new row
            Object[] rowData = new Object[] {
                product.getProductId(),
                product.getProductName(),
                actualOrderLine.getQuantity(),
                "£" + actualOrderLine.getLineTotal()
                
            };
            
            // Add the new row to the table
            powerModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrders = new javax.swing.JTable();
        btnAddMoreProducts = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        btnRemoveOrderLine = new javax.swing.JButton();
        lblTotalPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductId", "Product", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(lstOrders);

        btnAddMoreProducts.setText("Add More Products");
        btnAddMoreProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoreProductsActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        btnRemoveOrderLine.setText("Remove Selected Product");
        btnRemoveOrderLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderLineActionPerformed(evt);
            }
        });

        lblTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnAddMoreProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveOrderLine))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMoreProducts)
                    .addComponent(btnRemoveOrderLine))
                .addGap(18, 18, 18)
                .addComponent(btnBuy)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMoreProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoreProductsActionPerformed
        // TODO add your handling code here:
        BrowseProducts browseProducts = new BrowseProducts(this.currentBasket, this.loggedInCustomer);
        browseProducts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddMoreProductsActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        Payment payment = new Payment(this.loggedInCustomer,this.currentBasket);
        payment.setVisible(true);
        
        this.dispose();

    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnRemoveOrderLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderLineActionPerformed
        // TODO add your handling code here:
        //Get selected row index
        int selectedRow = lstOrders.getSelectedRow();
        
        if (selectedRow == -1)
        {
            JOptionPane.showMessageDialog(this,"Error: Please Choose a Product to remove");
        }
        else
        {
            //Get product id from coloumn 0 of the selected row
            //parse to string, then to int
            String idString = lstOrders.getValueAt(selectedRow, 0).toString();
            int productId = Integer.parseInt(idString);
            
            //cqll method
            currentBasket.removeOrderLine(productId);
            
            //Update View and show confirmation
            JOptionPane.showMessageDialog(this, "Product successfully removed");
            populateTable();
            
            lblTotalPrice.setText("Total: £" + String.format("%.2f", currentBasket.getOrderTotal()) );
            
        }
    }//GEN-LAST:event_btnRemoveOrderLineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Basket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoreProducts;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnRemoveOrderLine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTable lstOrders;
    // End of variables declaration//GEN-END:variables
}
