/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Customer;
import models.Order;
import models.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author 30512007
 */
public class CustomerHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerHome.class.getName());

    private Customer loggedInCustomer;
    
    /**
     * Creates new form CustomerHome
     */
    public CustomerHome() {
        initComponents();
        this.loggedInCustomer=null;
    }
    
    public CustomerHome(Customer customerIn)
    {
        initComponents();
        this.loggedInCustomer = customerIn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrowseProducts = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        btnEditDetails = new javax.swing.JButton();
        btnUnregisterFromShop = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBrowseProducts.setText("BROWSE PRODUCTS");
        btnBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseProductsActionPerformed(evt);
            }
        });

        btnViewOrders.setText("VIEW MY ORDERS");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });

        btnEditDetails.setText("EDIT DETAILS");
        btnEditDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDetailsActionPerformed(evt);
            }
        });

        btnUnregisterFromShop.setText("UNREGISTER FROM SHOP");
        btnUnregisterFromShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnregisterFromShopActionPerformed(evt);
            }
        });

        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnUnregisterFromShop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewOrders)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBrowseProducts)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(btnEditDetails))))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnBrowseProducts)
                .addGap(18, 18, 18)
                .addComponent(btnViewOrders)
                .addGap(18, 18, 18)
                .addComponent(btnEditDetails)
                .addGap(18, 18, 18)
                .addComponent(btnUnregisterFromShop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProductsActionPerformed
        // TODO add your handling code here:
        BrowseProducts browseProducts = new BrowseProducts(new Order(), this.loggedInCustomer);
        browseProducts.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBrowseProductsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnUnregisterFromShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnregisterFromShopActionPerformed
        // TODO add your handling code here:
        String username = loggedInCustomer.getUsername();
        
        int choice = JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to unregister?\nAll your details and order history will be permanently deleted.", 
            "Confirm Unregister", 
            JOptionPane.YES_NO_OPTION, // Gives "Yes" and "No" buttons
            JOptionPane.WARNING_MESSAGE // Shows a warning icon
        );
        
        if (choice == JOptionPane.YES_OPTION)
        {
            DBManager db = new DBManager();
            db.unregisterCustomer(username);
            
            JOptionPane.showMessageDialog(this, "You have been successfully unregistered.");
            
            MainMenu mainMenu = new MainMenu();
            mainMenu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnUnregisterFromShopActionPerformed

    private void btnEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDetailsActionPerformed
        // TODO add your handling code here:
        EditCustomer editCustomer = new EditCustomer(this.loggedInCustomer);
        editCustomer.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnEditDetailsActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        // TODO add your handling code here:
        CustomerOrders customerOrders = new CustomerOrders(this.loggedInCustomer);
        customerOrders.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseProducts;
    private javax.swing.JButton btnEditDetails;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUnregisterFromShop;
    private javax.swing.JButton btnViewOrders;
    // End of variables declaration//GEN-END:variables
}
