/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import models.Customer;
import models.DBManager;
import models.Order;
import models.OrderLine;
import models.Product;

/**
 *
 * @author thomm
 */
public class Payment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Payment.class.getName());

    private Order currentBasket;
    private Customer loggedInCustomer;
    /**
     * Creates new form Payment
     */
    public Payment(Customer customer, Order basket) {
        initComponents();
        this.loggedInCustomer = customer;
        this.currentBasket = basket;
        
        show_cards();
    }

    private String maskCardNumber(String realCardNumber)
    {
        //If input is null or short
        if (realCardNumber == null || realCardNumber.length()<8)
        {
            JOptionPane.showMessageDialog(this, "Enter a valid Card");
            return realCardNumber;
        }
        String lastFour = realCardNumber.substring(realCardNumber.length()-4);
        
        return "**** **** ****" + lastFour;
    }
    
    public void show_cards()
    {
        DefaultListModel<String> cardsModel = new DefaultListModel();
        for (String card: loggedInCustomer.getCardNumbers())
        {
            cardsModel.addElement(String.valueOf(card));
        }
        lstCardNo.setModel(cardsModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCardNo = new javax.swing.JList<>();
        txtCardNo = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnDeleteCard = new javax.swing.JButton();
        btnDefaultAdd = new javax.swing.JButton();
        txtDefault = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Card Number:");

        jLabel2.setText("Select Card Number:");

        jScrollPane1.setViewportView(lstCardNo);

        btnAdd.setText("Add Card");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm Payement Method");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnDeleteCard.setText("Delete Selected Card");
        btnDeleteCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCardActionPerformed(evt);
            }
        });

        btnDefaultAdd.setText("Add Card");
        btnDefaultAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultAddActionPerformed(evt);
            }
        });

        txtDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefaultActionPerformed(evt);
            }
        });

        jLabel3.setText("Add New Default card:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(jLabel3)
                    .addComponent(txtDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefaultAdd)
                    .addComponent(btnDeleteCard)
                    .addComponent(btnConfirm))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDefaultAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnBack))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        if (lstCardNo.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Please select a Card to pay with");
            return;
        }
        String selectedCard = lstCardNo.getSelectedValue();
        currentBasket.calculateOrderTotal();
        currentBasket.setPaymentCard(selectedCard);

        DBManager db = new DBManager();
        
        int newOrderId = db.saveOrder(currentBasket, loggedInCustomer.getUsername()); 
        
        if (newOrderId>0) {
        
            for (OrderLine ol : currentBasket.getOrderLines().values()) 
            {
                db.writeOrderLine(ol, newOrderId);
                
                Product product = ol.getProductBought();
                int quantity = ol.getQuantity();
                
                //update the stock
                db.updateStockLevel(product, quantity);
            }
            
            JOptionPane.showMessageDialog(this, "Order placed successfully!");
            Confirmation confirmFrame = new Confirmation(this.loggedInCustomer);
            confirmFrame.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error placing order. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String rawCardNum = txtCardNo.getText();
        if (rawCardNum.length() < 8)
        {
            JOptionPane.showMessageDialog(this, "Error: Enter a Valid Card Number");
            return;
        }
        String secureCard = maskCardNumber(rawCardNum);
        
        loggedInCustomer.addCard(secureCard);
        
        txtCardNo.setText("");
        show_cards();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDefaultAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultAddActionPerformed
        // TODO add your handling code here:
        String rawCardNum = txtDefault.getText();
        if (rawCardNum.length() < 8)
        {
            JOptionPane.showMessageDialog(this, "Error: Enter a Valid Card Number");
            return;
        }
        String secureCard = maskCardNumber(rawCardNum);
        
        loggedInCustomer.addFirstCard(secureCard);
        
        txtCardNo.setText("");
        show_cards();
        
    }//GEN-LAST:event_btnDefaultAddActionPerformed

    private void btnDeleteCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCardActionPerformed
        // TODO add your handling code here:
        
        if (lstCardNo.getSelectedIndex() == - 1)
        {
            JOptionPane.showMessageDialog(this, "Error: Select a Card Number First");
        }
        else
        {
            loggedInCustomer.removeCard(lstCardNo.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Success: Card Number Successfully Removed");
            show_cards();
        }
    }//GEN-LAST:event_btnDeleteCardActionPerformed

    private void txtDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDefaultActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Basket basket = new Basket(this.currentBasket, this.loggedInCustomer);
        basket.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Payment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDefaultAdd;
    private javax.swing.JButton btnDeleteCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstCardNo;
    private javax.swing.JTextField txtCardNo;
    private javax.swing.JTextField txtDefault;
    // End of variables declaration//GEN-END:variables
}
