/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import models.DBManager;
import models.Product;
import models.Staff;

/**
 *
 * @author 30512007
 */
public class ProductMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductMenu.class.getName());

    private ArrayList<Product> allProducts;
    
    private Staff loggedInStaff;
    /**
     * Creates new form ProductMenu
     */
    public ProductMenu(Staff staffIn) {
        DBManager db = new DBManager();
        allProducts = db.loadProducts();
        
        initComponents();
        
        this.loggedInStaff = staffIn;       
        
        lstProduct.setModel(new DefaultListModel<Product>());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProduct = new javax.swing.JList<>();
        btnEditProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBubbleSort = new javax.swing.JButton();
        btnSelectionSort = new javax.swing.JButton();
        txtSearchPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLinearSearch = new javax.swing.JButton();
        btnBinarySearch = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));

        jButton1.setText("RETURN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CATEGORIES");

        jLabel3.setText("PRODUCTS");

        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Heatpump", "SolarPanel", "Replacement_Parts" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategories);

        lstProduct.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProductValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstProduct);

        btnEditProduct.setText("EDIT PRODUCT");
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("DELETE PRODUCT");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Sort By:");

        btnBubbleSort.setText("Bubble Sort");
        btnBubbleSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleSortActionPerformed(evt);
            }
        });

        btnSelectionSort.setText("Selection Sort");
        btnSelectionSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionSortActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Product Price:");

        btnLinearSearch.setText("Linear Search");
        btnLinearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinearSearchActionPerformed(evt);
            }
        });

        btnBinarySearch.setText("Binary Search");
        btnBinarySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarySearchActionPerformed(evt);
            }
        });

        btnAddProduct.setText("ADD PRODUCT");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(txtSearchPrice)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBubbleSort, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelectionSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLinearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBinarySearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteProduct))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jButton1))
                                .addGap(82, 82, 82)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBubbleSort)
                    .addComponent(btnSelectionSort)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinearSearch)
                    .addComponent(btnBinarySearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteProduct)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditProduct)
                        .addComponent(btnAddProduct)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstProductValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstProductValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StaffHome staffHome = new StaffHome(this.loggedInStaff);
        staffHome.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        // TODO add your handling code here:
        
        String selectedCategory = lstCategories.getSelectedValue();
        DefaultListModel<Product> productsModel = new DefaultListModel<>();
        
        // Loop through all products
        for (Product p : allProducts)
        {
            
            if(p.getClass().getName().equals("models." + selectedCategory))
            {
                // It's a match! Add it to the list.
                productsModel.addElement(p);
            }
        }
        // Update the listbox with the filtered list
        lstProduct.setModel(productsModel);
    }//GEN-LAST:event_lstCategoriesValueChanged

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        // TODO add your handling code here:
        if (lstProduct.getSelectedIndex()!= -1)
        {
            Object selectedProductObject = (Object)lstProduct.getSelectedValue();
            Product selectedProduct = (Product) selectedProductObject;
            
            EditProduct editProduct = new EditProduct(this.loggedInStaff,selectedProduct);
            editProduct.setVisible(true);
            this.dispose();
            
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, "Choose a Product First", "Product Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
        if (lstProduct.getSelectedIndex() != -1)
        {
            
            Product selectedProduct = lstProduct.getSelectedValue();
            
            DBManager db = new DBManager();
            db.deleteProduct(selectedProduct.getProductId());
            
            DefaultListModel productModel = (DefaultListModel)lstProduct.getModel();
            productModel.remove(lstProduct.getSelectedIndex());
            
            allProducts = db.loadProducts();
            
            JOptionPane.showMessageDialog(this, "Deleted Product successfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error:Select Animal First");
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnBubbleSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleSortActionPerformed
        // TODO add your handling code here:
        //Get items from the list, and not the database
        DefaultListModel<Product> currentModel = (DefaultListModel<Product>) lstProduct.getModel();
        ArrayList<Product> productList = new ArrayList<>();
        
        //copy items from list to array list
        for (int i = 0; i < currentModel.getSize();i++)
        {
            productList.add(currentModel.getElementAt(i));
        }
        
        //Bubble Sort (Sort ArrayList)
        int n = productList.size();
        //use boolean flagto control if another pass through the list is needed
        boolean swapRequired = true;
        
        //Outer Loop
        //The while loop  keeps running as long as a swap happened in the previous pass
        //If no swaps occur, the list is orted and is stopped
        while (swapRequired)
        {
            swapRequired = false; //Assume sorted until proven
            
            //Loop stops at size -2 to compare a with a+1
            for (int a=0; a<= n -2; a++)
            {
                //Compare Price
                if (productList.get(a).getPrice() > productList.get(a+1).getPrice())
                {
                    //Swap
                    Product temp = productList.get(a);
                    productList.set(a, productList.get(a+1));
                    productList.set(a+1,temp);
                    
                    swapRequired = true;
                    
                }
            }
        }
        
        //Updating the List Box 
        //Clear Existing list and add sorted list back
        currentModel.clear();
        for (Product p : productList)
        {
            currentModel.addElement(p);
        }
    }//GEN-LAST:event_btnBubbleSortActionPerformed

    private void btnSelectionSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionSortActionPerformed
        // TODO add your handling code here:
        //Get items from the list, and not the database
        DefaultListModel<Product> currentModel = (DefaultListModel<Product>) lstProduct.getModel();
        ArrayList<Product> productList = new ArrayList<>();
        
        //copy items from list to array list
        for (int i = 0; i < currentModel.getSize();i++)
        {
            productList.add(currentModel.getElementAt(i));
        }
        
        //Selection Sort
        //GO through each position we want to place the cheapest product
        //a is the position are currently tyring to fit correctly
        int n = productList.size();
        
        
        for (int a = 0; a<n-1; a++)
        {
            //Assume product at a is cheapest for now
            int min = a;
            //look through list to find actual cheapest
            for (int b = a+1; b<n; b++)
            {
                if (productList.get(min).getPrice()>productList.get(b).getPrice())
                {
                    min=b; //update the index of cheapest product
                }
            }
            
            //Swap the product at position a with the cheapest one we found at min
            Product tempProduct = productList.get(a);
            productList.set(a,productList.get(min)); 
            productList.set(min, tempProduct);
            
        }
        
        //Update GUI
        currentModel.clear();
        for (Product p: productList)
        {
            currentModel.addElement(p);
        }
    }//GEN-LAST:event_btnSelectionSortActionPerformed

    private void btnLinearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinearSearchActionPerformed
        // TODO add your handling code here:
        DefaultListModel resultModel = new DefaultListModel();
        
        try
        {
            double targetPrice = Double.parseDouble(txtSearchPrice.getText());
            
            //Get current List of products from screen
            ListModel<Product> currentList = lstProduct.getModel();
            boolean isFound = false; //Glag to remeber if its found
            
            //Loop to go through every product in the List
            for (int i = 0; i < currentList.getSize(); i++)
            {
                Product p = currentList.getElementAt(i);
                
                //Compare to check if the products price match the target
                if (p.getPrice() == targetPrice)
                {
                    isFound = true;
                    resultModel.addElement(p);
                }
            }
            //If not found
            if(isFound  == false)
            {
                resultModel.addElement("Not Found");
            }
            
            //Updating Screen
            lstProduct.setModel(resultModel);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Please enter a valid Number for price");
        }
    }//GEN-LAST:event_btnLinearSearchActionPerformed

    private void btnBinarySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarySearchActionPerformed
        // TODO add your handling code here:
        DefaultListModel resultModel = new DefaultListModel();
        
        try
        {
            double targetPrice = Double.parseDouble(txtSearchPrice.getText());
            //Get current List of products from screen
            //COnvert ListModel to ArrayList for easier index access
            ListModel<Product> currentModel = lstProduct.getModel();
            ArrayList<Product> productList = new ArrayList<>();
            
            for (int i = 0; i < currentModel.getSize(); i++)
            {
                productList.add(currentModel.getElementAt(i));
            }
            
            //Define Search Boundaries
            int min = 0;
            int max = productList.size() - 1;
            
            //Loop to keep searching while the range is valid
            while (min<= max)
            {
                //FInding the middle Position
                int middle= (min + max)/2;
                Product middleProduct = productList.get(middle);
                
                //Check the mIDdle
                if (middleProduct.getPrice() == targetPrice)
                {
                    //Found
                    resultModel.addElement(middleProduct);
                    lstProduct.setModel(resultModel);
                    return; //Stopping here if founf
                }
                else
                {
                    //Decide to go left or right
                    if (targetPrice < middleProduct.getPrice())
                    {
                        //Target is smaller (cheaper) search left
                        max = middle - 1;
                    }
                    else
                    {
                        //Target is larger (expensive) search right
                        min = middle +1;
                    }
                }
            }
            //If loop finishes and didnt find it
            resultModel.addElement("Not Found");
            lstProduct.setModel(resultModel);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for price");
        }
    }//GEN-LAST:event_btnBinarySearchActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        AddProduct addProduct = new AddProduct(this.loggedInStaff);
        addProduct.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ProductMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBinarySearch;
    private javax.swing.JButton btnBubbleSort;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnLinearSearch;
    private javax.swing.JButton btnSelectionSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<Product> lstProduct;
    private javax.swing.JTextField txtSearchPrice;
    // End of variables declaration//GEN-END:variables
}
